{{- if $.Values._tests }}
{{- include "fl.expandIncludesInValues" (list $ $.Values) }}
{{- range list "" }}

---
kind: TestContainerEnvs
testContainerEnvs:
  env: {{ include "fl.generateContainerEnvVars" (list $ . $.Values.envs.env) | nindent 4 }}

---
kind: TestConfigMapEnvs
testConfigMapEnvs:
  env: {{ include "fl.generateConfigMapEnvVars" (list $ . $.Values.envs.env) | nindent 4 }}

---
kind: TestSecretEnvs
testConfigMapEnvs:
  env: {{ include "fl.generateSecretEnvVars" (list $ . $.Values.envs.env) | nindent 4 }}

---
kind: TestInclude
valuesDump: {{ $.Values.include | toYaml | nindent 4 }}

---
kind: TestIsTrue
testIsTrue:
  "yes": >-
    {{ if include "fl.isTrue" (list $ . $.Values.isTrueOrFalse.true) -}}
      yes
    {{- end }}
  "no": >-
    {{ if not (include "fl.isTrue" (list $ . $.Values.isTrueOrFalse.false)) -}}
      no
    {{- end }}
testIsFalse:
  "yes": >-
    {{ if include "fl.isFalse" (list $ . $.Values.isTrueOrFalse.false) -}}
      yes
    {{- end }}
  "no": >-
    {{ if not (include "fl.isFalse" (list $ . $.Values.isTrueOrFalse.true)) -}}
      no
    {{- end }}

---
kind: TestResources
testResources:
  none: {{ include "fl.generateContainerResources" (list $ . $.Values.resources.none) | nindent 4 }}
  empty: {{ include "fl.generateContainerResources" (list $ . $.Values.resources.empty) | nindent 4 }}
  onlyRequests: {{ include "fl.generateContainerResources" (list $ . $.Values.resources.onlyRequests) | nindent 4 }}
  all: {{ include "fl.generateContainerResources" (list $ . $.Values.resources.all) | nindent 4 }}
  multiEnv: {{ include "fl.generateContainerResources" (list $ . $.Values.resources.multiEnv) | nindent 4 }}

---
kind: TestVal
testValTypes:
  string: {{ include "fl.value" (list $ . $.Values.val.string) }}
  emptyString: {{ include "fl.value" (list $ . $.Values.val.emptyString) }}
  booleanFalse: {{ include "fl.value" (list $ . $.Values.val.booleanFalse) }}
  booleanTrue: {{ include "fl.value" (list $ . $.Values.val.booleanTrue) }}
  number: {{ include "fl.value" (list $ . $.Values.val.number) }}
  nullType: {{ include "fl.value" (list $ . $.Values.val.nullType) }}
  nilType: {{ include "fl.value" (list $ . $.Values.val.nilType) }}
  map: {{ include "fl.value" (list $ . $.Values.val.map) | nindent 4 }}
  emptyMap: {{ include "fl.value" (list $ . $.Values.val.emptyMap) | nindent 4 }}
  list: {{ include "fl.value" (list $ . $.Values.val.list) | nindent 4 }}
  emptyList: {{ include "fl.value" (list $ . $.Values.val.emptyList) | nindent 4 }}
testValQTypes:
  string: {{ include "fl.valueQuoted" (list $ . $.Values.val.string) }}
  emptyString: {{ include "fl.valueQuoted" (list $ . $.Values.val.emptyString) }}
  booleanFalse: {{ include "fl.valueQuoted" (list $ . $.Values.val.booleanFalse) }}
  booleanTrue: {{ include "fl.valueQuoted" (list $ . $.Values.val.booleanTrue) }}
  number: {{ include "fl.valueQuoted" (list $ . $.Values.val.number) }}
  nullType: {{ include "fl.valueQuoted" (list $ . $.Values.val.nullType) }}
  nilType: {{ include "fl.valueQuoted" (list $ . $.Values.val.nilType) }}
testValSQTypes:
  string: {{ include "fl.valueSingleQuoted" (list $ . $.Values.val.string) }}
  emptyString: {{ include "fl.valueSingleQuoted" (list $ . $.Values.val.emptyString) }}
  booleanFalse: {{ include "fl.valueSingleQuoted" (list $ . $.Values.val.booleanFalse) }}
  booleanTrue: {{ include "fl.valueSingleQuoted" (list $ . $.Values.val.booleanTrue) }}
  number: {{ include "fl.valueSingleQuoted" (list $ . $.Values.val.number) }}
  nullType: {{ include "fl.valueSingleQuoted" (list $ . $.Values.val.nullType) }}
  nilType: {{ include "fl.valueSingleQuoted" (list $ . $.Values.val.nilType) }}
testValEnvs:
  multiEnv: {{ include "fl.value" (list $ . $.Values.val.multiEnv) }}
  onlyDefaultEnv: {{ include "fl.value" (list $ . $.Values.val.onlyDefaultEnv) }}
  onlyCustomEnv: {{ include "fl.value" (list $ . $.Values.val.onlyCustomEnv) }}
  multiEnvBooleanFalse: {{ include "fl.value" (list $ . $.Values.val.multiEnvBooleanFalse) }}
testValTemplating:
  template: {{ include "fl.value" (list $ . $.Values.val.template) }}
testValPrefixSuffix:
  prefix: {{ include "fl.value" (list $ . "body" (dict "prefix" $.Values.val.prefix)) }}
  suffix: {{ include "fl.value" (list $ . "body" (dict "suffix" $.Values.val.suffix)) }}

---
kind: TestLabels
testLabels:
  labels: {{ include "fl.generateLabels" (list $ . $.Values.global.werf.name) | nindent 4 }}

---
kind: TestImage
testImage:
  onlyStatic: {{ include "fl.generateContainerImageQuoted" (list $ . $.Values.image.onlyStatic) }}
  onlySignatureBased: {{ include "fl.generateContainerImageQuoted" (list $ . $.Values.image.onlySignatureBased) }}
  both: {{ include "fl.generateContainerImageQuoted" (list $ . $.Values.image.both) }}

---
kind: TestFormatString
testFormatStringAsDNSSubdomain: {{ $.Values.brokenName | include "fl.formatStringAsDNSSubdomain" | quote }}
testFormatStringAsDNSLabel: {{ $.Values.brokenName | include "fl.formatStringAsDNSLabel" | quote }}

{{- end }}
{{- end }}
