name: main

env:
  WERF_VERSION: "1.1 ea"
  CHARTMUSEUM_URL: "https://charts.flant.com/api/bravo/libs/"
  CHARTMUSEUM_BASIC_AUTH_USER: "${{ secrets.CHARTMUSEUM_BASIC_AUTH_USER }}"
  CHARTMUSEUM_BASIC_AUTH_PASS: "${{ secrets.CHARTMUSEUM_BASIC_AUTH_PASS }}"

on:
  push:
  pull_request:
    types: "[opened, synchronize, reopened]"

defaults:
  run:
    shell: "bash -l -eo pipefail {0}"

jobs:
  tests:
    runs-on: "ubuntu-18.04"
    strategy:
      matrix:
        werf_commands: ["lint", "render"]
    steps:
      - uses: "actions/checkout@v2"
      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install python3 python3-pip python3-setuptools
          sudo pip3 install -r requirements.txt
      - name: Setup werf
        run: |
          mkdir -p ~/bin
          cd ~/bin
          curl -sSL https://raw.githubusercontent.com/werf/multiwerf/master/get.sh | bash
          echo "$HOME/bin" >> $GITHUB_PATH
          echo "source <(multiwerf use $WERF_VERSION)" >> ~/.bash_profile
      - name: Werf ${{ matrix.werf_commands }} charts
        run: |
          while read chart_name; do
            for env in "test" "prod"; do
              set -x
              werf helm ${{ matrix.werf_commands }} --env "$env" --set "${chart_name}.enabled=true" --set "global.ci_url=example.org"
              set +x
            done
          done < <(find .helm/charts -type d -mindepth 1 -maxdepth 1 -exec sh -c 'basename "$1"' sh '{}' \;)
  # publish-charts:
  #   runs-on: "ubuntu-18.04"
  #   if: "github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'flant/helm-charts'"
  #   needs: "tests"
  #   steps:
  #     - uses: "actions/checkout@v2"
  #     - name: Install dependencies
  #       run: |
  #         sudo apt-get -qq update
  #         sudo apt-get -qq install python3 python3-pip python3-setuptools
  #         sudo pip3 install -r requirements.txt
  #     - name: Package werf charts
  #       run: 'doit werf-package-charts'
  #     - name: Publish packaged werf charts
  #       run: 'doit werf-publish-chart-packages'
