name: main

env:
  DOIT_WERF_VERSION: "1.1 ea"
  DOIT_CHARTMUSEUM_BASIC_AUTH_USER: "${{ secrets.CHARTMUSEUM_BASIC_AUTH_USER }}"
  DOIT_CHARTMUSEUM_BASIC_AUTH_PASS: "${{ secrets.CHARTMUSEUM_BASIC_AUTH_PASS }}"
  DOIT_CHARTMUSEUM_URL: "https://charts.flant.com/"

on:
  push:
  pull_request:
    types: "[opened, synchronize, reopened]"

jobs:
  tests:
    runs-on: "ubuntu-18.04"
    steps:
      - uses: "actions/checkout@v2"
      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install python3 python3-pip python3-setuptools
          sudo pip3 install -r requirements.txt
      - name: Setup multiwerf
        run: |
          mkdir -p ~/bin
          cd ~/bin
          curl -sSL https://raw.githubusercontent.com/werf/multiwerf/master/get.sh | bash
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Werf lint charts
        run: 'doit werf-lint'
      - name: Werf render charts
        run: 'doit werf-render'
  publish-charts:
    runs-on: "ubuntu-18.04"
    if: "github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'flant/helm-charts'"
    needs: "tests"
    steps:
      - uses: "actions/checkout@v2"
      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install python3 python3-pip python3-setuptools
          sudo pip3 install -r requirements.txt
      - name: Package werf charts
        run: 'doit werf-package-charts'
      - name: Publish packaged werf charts
        run: 'doit werf-publish-chart-packages'
