name: main

env:
  WERF_VERSION: "1.1 ea"
  CHARTMUSEUM_URL: "https://charts.flant.com/api/common/github/charts"

on:
  push:
  pull_request:
    types: "[opened, synchronize, reopened]"

defaults:
  run:
    shell: "bash -l -eo pipefail {0}"

jobs:
  tests:
    runs-on: "ubuntu-18.04"
    steps:
      - uses: "actions/checkout@v2"
      - name: Setup werf
        run: |
          mkdir -p ~/bin
          cd ~/bin
          curl -sSL https://raw.githubusercontent.com/werf/multiwerf/master/get.sh | bash
          echo "$HOME/bin" >> $GITHUB_PATH
          echo "source <(multiwerf use $WERF_VERSION)" >> ~/.bash_profile
      - name: Werf lint/render charts
        run: |
          while read chart_name; do
            for env in "test" "prod"; do
              set -x
              werf helm lint --env "$env" --set "${chart_name}.enabled=true" --set "global.ci_url=example.org"
              werf helm render --env "$env" --set "${chart_name}.enabled=true" --set "global.ci_url=example.org"
              set +x
            done
          done < <(find .helm/charts -mindepth 1 -maxdepth 1 -type d -exec sh -c 'basename "$0"' '{}' \;)
  publish-charts:
    runs-on: "ubuntu-18.04"
    if: "github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'flant/helm-charts'"
    needs: "tests"
    steps:
      - uses: "actions/checkout@v2"
      - name: Package werf charts
        run: |
          mkdir -p .packages
          helm package .helm/charts/flant-lib -d .packages
      - name: Publish packaged werf charts
        run: |
          while read package; do
            curl -sSL --post301 --data-binary "@.packages/$package" --user "${{ secrets.CHARTMUSEUM_BASIC_AUTH_USER }}:${{ secrets.CHARTMUSEUM_BASIC_AUTH_PASS }}" "$CHARTMUSEUM_URL"
          done < <(find .packages -mindepth 1 -maxdepth 1 -type f -name '*.tgz' -exec sh -c 'basename "$0"' '{}' \;)
